<!DOCTYPE html>
<html lang="<?= LC_LANG ?>">
	<head>
		<meta charset="utf-8">
		<title><?= LC_TITLE ?></title>
		<meta name="description" content="">
		<meta name="author" content="Vivien Richter">
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="stylesheet" href="<?= BASEPATH.DIRECTORY_SEPARATOR.'themes'.DIRECTORY_SEPARATOR.CFG_THEME.DIRECTORY_SEPARATOR.'css'.DIRECTORY_SEPARATOR.'calculate.css' ?>">
	</head>

	<body>
		<header>
			<h1><?= LC_HEADLINE ?></h1>
		</header>

		<div>
		</div>

		<footer>
			<p>
				&copy; Copyright 2016 by Vivien Richter
			</p>
		</footer>
	</body>
</html>
